name: build-and-push

on:
  workflow_dispatch:
    inputs:
      base_tag:
        description: "Base Mautic tag (e.g., 6-fpm or 6.0.4-fpm)"
        required: true
        default: "6-fpm"
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: andresasm/mautic
      BASE_TAG: ${{ github.event.inputs.base_tag || '6-fpm' }}
      PUSH_TAG: ${{ github.event.inputs.base_tag || '6-fpm' }}-sendgrid

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          build-args: |
            BASE_TAG=${{ env.BASE_TAG }}
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.PUSH_TAG }}
            # Optional convenience tags:
            # ${{ env.IMAGE_NAME }}:${{ env.BASE_TAG }}-sendgrid-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
